import {
  IconAlertTriangle,
  IconArchive,
  IconBellRinging,
  IconBuildingStore,
  IconCalendarStats,
  IconCash,
  IconChartBar,
  IconChartDots,
  IconChefHat,
  IconClockHour4,
  IconCreditCard,
  IconDatabaseDollar,
  IconDiscount2,
  IconFileInvoice,
  IconFlame,
  IconHeartHandshake,
  IconHistory,
  IconListDetails,
  IconReceiptTax,
  IconRefresh,
  IconReportAnalytics,
  IconReportMoney,
  IconShoppingBag,
  IconStar,
  IconTable,
  IconTags,
  IconTicket,
  IconToolsKitchen2,
  IconTrendingDown,
  IconTrendingUp,
  IconTruckDelivery,
  IconUsers,
  IconWallet,
} from "@tabler/icons-react";

export const REPORT_CATEGORIES = [
  "Sales",
  "Payments",
  "Menu",
  "Customers",
  "Operations",
  "Inventory",
  "Accounting",
  "Reservations",
  "Feedback",
];

export const REPORT_CATALOG = [
  {
    id: "sales-summary",
    title: "Sales Summary",
    category: "Sales",
    description: "Revenue, net sales, taxes, service charge, orders, AOV, customers, top items, and payment split.",
    icon: IconReportAnalytics,
    status: "ready",
    priority: "Core",
  },
  {
    id: "gross-sales",
    title: "Gross Sales",
    category: "Sales",
    description: "Total item sales before taxes, service charges, refunds, voids, and discounts.",
    icon: IconTrendingUp,
    status: "ready",
    priority: "Core",
  },
  {
    id: "net-sales",
    title: "Net Sales",
    category: "Sales",
    description: "Sales after discounts and voids, separated by tax, service charge, and payment total.",
    icon: IconReportMoney,
    status: "ready",
    priority: "Core",
  },
  {
    id: "sales-by-hour",
    title: "Sales by Hour",
    category: "Sales",
    description: "Hourly sales trend to understand rush windows and quiet periods.",
    icon: IconClockHour4,
    status: "ready",
    priority: "High",
  },
  {
    id: "sales-by-day",
    title: "Sales by Day",
    category: "Sales",
    description: "Daily sales totals, order counts, average ticket, and customer count.",
    icon: IconCalendarStats,
    status: "ready",
    priority: "High",
  },
  {
    id: "sales-by-month",
    title: "Sales by Month",
    category: "Sales",
    description: "Monthly revenue trend for owner-level business review.",
    icon: IconChartDots,
    status: "ready",
    priority: "High",
  },
  {
    id: "sales-by-order-type",
    title: "Sales by Order Type",
    category: "Sales",
    description: "Dine-in, takeaway, delivery, QR ordering, and other delivery type performance.",
    icon: IconTruckDelivery,
    status: "ready",
    priority: "Core",
  },
  {
    id: "sales-by-table",
    title: "Sales by Table",
    category: "Sales",
    description: "Revenue, orders, and average ticket grouped by dining table and floor.",
    icon: IconTable,
    status: "ready",
    priority: "High",
  },
  {
    id: "invoice-detail",
    title: "Invoice Detail",
    category: "Sales",
    description: "Line-by-line invoice totals with payment method, tax, service charge, and customer.",
    icon: IconFileInvoice,
    status: "ready",
    priority: "Core",
  },
  {
    id: "voids-cancellations",
    title: "Voids & Cancellations",
    category: "Sales",
    description: "Cancelled orders and cancelled items with quantities and lost sales value.",
    icon: IconAlertTriangle,
    status: "ready",
    priority: "High",
  },
  // {
  //   id: "discounts",
  //   title: "Discounts",
  //   category: "Sales",
  //   description: "Discount impact by order, item, user, and date where discount data is available.",
  //   icon: IconDiscount2,
  //   status: "planned",
  //   priority: "Medium",
  // },
  {
    id: "average-order-value",
    title: "Average Order Value",
    category: "Sales",
    description: "Average ticket size trend across selected periods and service types.",
    icon: IconTicket,
    status: "ready",
    priority: "Core",
  },
  {
    id: "payment-summary",
    title: "Payment Summary",
    category: "Payments",
    description: "Payments grouped by cash, card, wallet, online, and custom payment types.",
    icon: IconCreditCard,
    status: "ready",
    priority: "Core",
  },
  {
    id: "cash-report",
    title: "Cash Report",
    category: "Payments",
    description: "Cash collections, cash invoices, and cash share of total payments.",
    icon: IconCash,
    status: "ready",
    priority: "High",
  },
  {
    id: "card-report",
    title: "Card Report",
    category: "Payments",
    description: "Card payment volume and transaction count by date and invoice.",
    icon: IconWallet,
    status: "ready",
    priority: "High",
  },
  {
    id: "unpaid-orders",
    title: "Unpaid Orders",
    category: "Payments",
    description: "Orders with pending payment status for follow-up and closing checks.",
    icon: IconBellRinging,
    status: "ready",
    priority: "Core",
  },
  {
    id: "payment-type-mix",
    title: "Payment Type Mix",
    category: "Payments",
    description: "Share of revenue by payment method with trend and comparison support.",
    icon: IconChartBar,
    status: "ready",
    priority: "Medium",
  },
  {
    id: "top-selling-items",
    title: "Top Selling Items",
    category: "Menu",
    description: "Most sold menu items by quantity, revenue, category, and date range.",
    icon: IconFlame,
    status: "ready",
    priority: "Core",
  },
  {
    id: "low-selling-items",
    title: "Low Selling Items",
    category: "Menu",
    description: "Items with low movement so owners can simplify the menu.",
    icon: IconTrendingDown,
    status: "ready",
    priority: "Medium",
  },
  {
    id: "item-sales",
    title: "Item Sales",
    category: "Menu",
    description: "Detailed item revenue, quantity sold, net price, tax, and category.",
    icon: IconToolsKitchen2,
    status: "ready",
    priority: "Core",
  },
  {
    id: "category-sales",
    title: "Category Sales",
    category: "Menu",
    description: "Food, beverage, dessert, and custom category sales performance.",
    icon: IconTags,
    status: "ready",
    priority: "Core",
  },
  {
    id: "variant-sales",
    title: "Variant Sales",
    category: "Menu",
    description: "Size, preparation, and variant-level sales performance.",
    icon: IconListDetails,
    status: "ready",
    priority: "Medium",
  },
  {
    id: "addon-sales",
    title: "Addon Sales",
    category: "Menu",
    description: "Revenue and quantity from paid addons and modifiers.",
    icon: IconArchive,
    status: "ready",
    priority: "Medium",
  },
  {
    id: "menu-price-audit",
    title: "Menu Price Audit",
    category: "Menu",
    description: "Current item, variant, addon, net price, and tax setup for menu review.",
    icon: IconDatabaseDollar,
    status: "ready",
    priority: "Medium",
  },
  {
    id: "customer-summary",
    title: "Customer Summary",
    category: "Customers",
    description: "Total, new, returning, member, and guest customer performance.",
    icon: IconUsers,
    status: "ready",
    priority: "Core",
  },
  {
    id: "new-customers",
    title: "New Customers",
    category: "Customers",
    description: "Customers created during the selected period with contact details.",
    icon: IconUsers,
    status: "ready",
    priority: "High",
  },
  {
    id: "returning-customers",
    title: "Returning Customers",
    category: "Customers",
    description: "Customers who placed orders in the selected period.",
    icon: IconRefresh,
    status: "ready",
    priority: "High",
  },
  {
    id: "top-customers",
    title: "Top Customers",
    category: "Customers",
    description: "Best customers by spend, visits, and average ticket.",
    icon: IconStar,
    status: "ready",
    priority: "High",
  },
  {
    id: "customer-birthdays",
    title: "Customer Birthdays",
    category: "Customers",
    description: "Upcoming birthdays for campaigns and loyalty outreach.",
    icon: IconHeartHandshake,
    status: "ready",
    priority: "Medium",
  },
  {
    id: "member-customers",
    title: "Member Customers",
    category: "Customers",
    description: "Membership list and member sales contribution.",
    icon: IconUsers,
    status: "ready",
    priority: "Medium",
  },
  {
    id: "order-status",
    title: "Order Status",
    category: "Operations",
    description: "Created, completed, cancelled, paid, and pending order movement.",
    icon: IconHistory,
    status: "ready",
    priority: "Core",
  },
  {
    id: "kitchen-performance",
    title: "Kitchen Performance",
    category: "Operations",
    description: "Prepared, completed, cancelled, and delivered item status volume.",
    icon: IconChefHat,
    status: "ready",
    priority: "High",
  },
  {
    id: "token-report",
    title: "Token Report",
    category: "Operations",
    description: "Token sequence and order flow for counter service and food trucks.",
    icon: IconTicket,
    status: "ready",
    priority: "Medium",
  },
  {
    id: "qr-order-report",
    title: "QR Order Report",
    category: "Operations",
    description: "QR order volume, status, table, and customer mix.",
    icon: IconShoppingBag,
    status: "ready",
    priority: "High",
  },
  {
    id: "table-turnover",
    title: "Table Turnover",
    category: "Operations",
    description: "Orders and sales by table to identify high-use dining areas.",
    icon: IconTable,
    status: "ready",
    priority: "Medium",
  },
  {
    id: "staff-created-orders",
    title: "Staff Created Orders",
    category: "Operations",
    description: "Order and invoice activity by staff where user tracking is available.",
    icon: IconUsers,
    status: "ready",
    priority: "Medium",
  },
  {
    id: "inventory-summary",
    title: "Inventory Summary",
    category: "Inventory",
    description: "Current stock, units, thresholds, and stock status.",
    icon: IconArchive,
    status: "ready",
    priority: "Core",
  },
  {
    id: "low-stock",
    title: "Low Stock",
    category: "Inventory",
    description: "Ingredients and items below minimum threshold.",
    icon: IconAlertTriangle,
    status: "ready",
    priority: "Core",
  },
  {
    id: "stock-movements",
    title: "Stock Movements",
    category: "Inventory",
    description: "IN, OUT, and WASTAGE logs with before and after quantities.",
    icon: IconHistory,
    status: "ready",
    priority: "Core",
  },
  {
    id: "wastage",
    title: "Wastage",
    category: "Inventory",
    description: "Wastage quantity by ingredient, date, note, and staff.",
    icon: IconTrendingDown,
    status: "ready",
    priority: "High",
  },
  {
    id: "recipe-usage",
    title: "Recipe Usage",
    category: "Inventory",
    description: "Ingredient usage estimate from item recipes, variants, and addons.",
    icon: IconChefHat,
    status: "ready",
    priority: "Medium",
  },
  {
    id: "stock-reorder",
    title: "Reorder List",
    category: "Inventory",
    description: "Suggested restock list based on current stock and minimum thresholds.",
    icon: IconBellRinging,
    status: "ready",
    priority: "High",
  },
  {
    id: "tax-summary",
    title: "Tax Summary",
    category: "Accounting",
    description: "Tax collected by period with inclusive and exclusive tax setup.",
    icon: IconReceiptTax,
    status: "ready",
    priority: "Core",
  },
  {
    id: "tax-by-item",
    title: "Tax by Item",
    category: "Accounting",
    description: "Tax setup and taxable sales grouped by menu item.",
    icon: IconReceiptTax,
    status: "ready",
    priority: "Medium",
  },
  {
    id: "service-charge",
    title: "Service Charge",
    category: "Accounting",
    description: "Service charge total and share of revenue.",
    icon: IconCash,
    status: "ready",
    priority: "High",
  },
  {
    id: "daily-close",
    title: "Daily Close",
    category: "Accounting",
    description: "End-of-day sales, payment, taxes, service charge, and unpaid order snapshot.",
    icon: IconBuildingStore,
    status: "ready",
    priority: "Core",
  },
  {
    id: "invoice-register",
    title: "Invoice Register",
    category: "Accounting",
    description: "Chronological invoice ledger for accounting review.",
    icon: IconFileInvoice,
    status: "ready",
    priority: "Core",
  },
  {
    id: "reservation-summary",
    title: "Reservation Summary",
    category: "Reservations",
    description: "Reservations by status, people count, date, and table.",
    icon: IconCalendarStats,
    status: "ready",
    priority: "High",
  },
  {
    id: "upcoming-reservations",
    title: "Upcoming Reservations",
    category: "Reservations",
    description: "Future bookings with customer, table, people count, and notes.",
    icon: IconBellRinging,
    status: "ready",
    priority: "High",
  },
  {
    id: "reservation-no-show",
    title: "Reservation No-Show",
    category: "Reservations",
    description: "Booked reservations that did not convert into table activity where available.",
    icon: IconAlertTriangle,
    status: "ready",
    priority: "Medium",
  },
  {
    id: "feedback-summary",
    title: "Feedback Summary",
    category: "Feedback",
    description: "Average rating, food, service, staff, ambiance, and recommendation scores.",
    icon: IconStar,
    status: "ready",
    priority: "Core",
  },
  {
    id: "negative-feedback",
    title: "Negative Feedback",
    category: "Feedback",
    description: "Low-rated feedback and remarks for service recovery.",
    icon: IconAlertTriangle,
    status: "ready",
    priority: "High",
  },
  {
    id: "recommendation-score",
    title: "Recommendation Score",
    category: "Feedback",
    description: "Recommend rating trend and distribution by period.",
    icon: IconHeartHandshake,
    status: "ready",
    priority: "Medium",
  },
];
